Models/AthenaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SPV_Loader.Models
{
    public class AthenaViewModel
    {
        public IEnumerable<AthenaJob> AthenaList { get; set; }
        public AthenaJob AthenaDetails { get; set; }
    }
}

Controllers/AthenaController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using SPV_Loader.Models;

namespace SPV_Loader.Controllers
{
    public class AthenaController : Controller
    {
        private readonly string _connectionString = "Data Source=CM-APP-SVR\\SQLEXPRESS;Initial Catalog=SpvLoader;Integrated Security=true";

        // Track the current index
        private static int currentIndex = 0;
        private static List<AthenaJob> athenaJobs = null;

        public ActionResult Index()
        {
            if (athenaJobs == null)
            {
                athenaJobs = new List<AthenaJob>(); // Initialize as empty list
            }

            AthenaJob details = null;
            if (currentIndex < athenaJobs.Count)
            {
                details = athenaJobs[currentIndex]; // Get the details object for the current index
            }

            var viewModel = new AthenaViewModel
            {
                AthenaList = athenaJobs,
                AthenaDetails = details
            };

            if (currentIndex >= athenaJobs.Count && athenaJobs.Any())
            {
                currentIndex = 0; // Reset index if it exceeds the list
                athenaJobs = new List<AthenaJob>(); // Clear the list
                ViewBag.AllItemsProcessed = true;
            }
            else
            {
                ViewBag.AllItemsProcessed = false;
            }

            return View(viewModel);
        }

        public List<AthenaJob> GetItems()
        {
            List<AthenaJob> jobs = new List<AthenaJob>();
            try
            {
                using (SpvLoaderEntities context = new SpvLoaderEntities())
                {
                    jobs = context.AthenaJobs.ToList();
                }
            }
            catch (Exception ex)
            {
                // Log the error or handle it as needed
                TempData["errorMessage"] = ex.ToString();
            }
            return jobs;
        }

        public AthenaJob GetDetails(int id)
        {
            AthenaJob detail = null;
            try
            {
                using (SpvLoaderEntities context = new SpvLoaderEntities())
                {
                    detail = context.AthenaJobs.FirstOrDefault(d => d.Id == id);
                }
            }
            catch (Exception ex)
            {
                // Log the error or handle it as needed
                TempData["errorMessage"] = ex.ToString();
            }
            return detail;
        }

        [HttpPost]
        public ActionResult Save(AthenaViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (SpvLoaderEntities context = new SpvLoaderEntities())
                    {
                        var jobToUpdate = context.AthenaJobs.FirstOrDefault(j => j.Id == model.AthenaDetails.Id);

                        if (jobToUpdate != null)
                        {
                            // Update the job details with the values from the model
                            jobToUpdate.JobNumber = model.AthenaDetails.JobNumber;
                            jobToUpdate.DueDate = model.AthenaDetails.DueDate;
                            jobToUpdate.PurchaseOrderNumber = model.AthenaDetails.PurchaseOrderNumber;
                            jobToUpdate.PurchaseOrderLine = model.AthenaDetails.PurchaseOrderLine;
                            jobToUpdate.SalesOrderNumber = model.AthenaDetails.SalesOrderNumber;
                            jobToUpdate.CustomerAccountCode = model.AthenaDetails.CustomerAccountCode;
                            jobToUpdate.JobQuantity = model.AthenaDetails.JobQuantity;
                            jobToUpdate.AscmOrderId = model.AthenaDetails.AscmOrderId;
                            jobToUpdate.EndCustomer = model.AthenaDetails.EndCustomer;
                            jobToUpdate.ActivationSystem = model.AthenaDetails.ActivationSystem;
                            jobToUpdate.ProductType = model.AthenaDetails.ProductType;
                            jobToUpdate.ErpMaterialCode = model.AthenaDetails.ErpMaterialCode;
                            jobToUpdate.IntegratorPartID = model.AthenaDetails.IntegratorPartID;
                            jobToUpdate.IntegratorID = model.AthenaDetails.IntegratorID;
                            jobToUpdate.ActivationType = model.AthenaDetails.ActivationType;
                            jobToUpdate.PartNumberSku = model.AthenaDetails.PartNumberSku;
                            jobToUpdate.RetailBarcode = model.AthenaDetails.RetailBarcode;
                            jobToUpdate.RetailBarcodeType = model.AthenaDetails.RetailBarcodeType;
                            jobToUpdate.Channel = model.AthenaDetails.Channel;

                            // Save changes to the database
                            context.SaveChanges();
                        }
                    }
                }
                catch (Exception ex)
                {
                    // Log the error or handle it as needed
                    TempData["errorMessage"] = ex.ToString();
                }
            }

            // Move to the next item in the list
            currentIndex++;
            return RedirectToAction("Index");
        }

        // Method to set the athenaJobs list
        public void SetAthenaJobs(List<AthenaJob> jobs)
        {
            athenaJobs = jobs;
            currentIndex = 0; // Reset the index
        }

        // Download action for the processed list
        [HttpPost]
        public ActionResult Download()
        {
           

            return new EmptyResult();
        }
    }
}

Views/Athena/Index.cshtml
@model SPV_Loader.Models.AthenaViewModel

@{
    ViewBag.Title = "Index";
    bool isProcessingCompleted = ViewBag.AllItemsProcessed ?? false;
    WebGrid grid = new WebGrid(Model.AthenaList, canPage: false);
}

<h2><strong>ATHENA</strong></h2>

@if (!isProcessingCompleted)
{
    using (Html.BeginForm("ImportOrder", "ImportOrder", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div>
            <table>
                <tr>
                    <td>
                        <h4>Upload Order File</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="file" name="postedFile" />
                    </td>
                    <td>
                        <input type="submit" id="btn_Upload" value="Upload" aria-label="Load" />
                    </td>
                    <td>
                        @Html.ValidationSummary()
                        @TempData["errorMessage"]
                    </td>
                </tr>
            </table>
        </div>
    }

    <br />
    <div class="webgrid-container">
        <table class="table-responsive">
            <tr>
                <td>
                    @grid.GetHtml(
                    tableStyle: "webgrid-table",
                    fillEmptyRows: false,
                    headerStyle: "webgrid-header",
                    alternatingRowStyle: "webgrid-alternating-row",
                    selectedRowStyle: "select",
                    footerStyle: "grid-footer",
                    mode: WebGridPagerModes.All,
                    firstText: "<< First",
                    previousText: "< Prev",
                    nextText: "Next >",
                    lastText: "Last >>",
                    columns: new[]
                    {
                        grid.Column("JobNumber", canSort: false),
                        grid.Column("DueDate", canSort: false, style: "noWrap"),
                        grid.Column("PurchaseOrderNumber", canSort: false),
                        grid.Column("PurchaseOrderLine", canSort: false),
                        grid.Column("SalesOrderNumber", canSort: false),
                        grid.Column("CustomerAccountCode", canSort: false),
                        grid.Column("JobQuantity", canSort: false),
                        grid.Column("ASCMOrderId", canSort: false),
                        grid.Column("EndCustomer", canSort: false),
                        grid.Column("ActivationSystem", canSort: false),
                        grid.Column("ProductType", canSort: false),
                        grid.Column("ErpMaterialCode", canSort: false),
                        grid.Column("IntegratorPartId", canSort: false),
                        grid.Column("ActivationType", canSort: false),
                        grid.Column("PartNumberSku", canSort: false, style: "noWrap"),
                        grid.Column("RetailBarcode", canSort: false),
                    })
                </td>
            </tr>
        </table>
    </div>
    
}
else
{
    <p>All items have been processed.</p>
    <form action="@Url.Action("Download", "Athena")" method="post">
    </form>
}

<hr />
@Html.Partial("_AthenaJob", Model)

<style type="text/css">
    .noWrap {
        width: 100px; /* Fixed width for the column */
        white-space: nowrap; /* Prevent text from wrapping */
        overflow: hidden; /* Hide overflow text */
        text-overflow: ellipsis; /* Show ellipsis when text overflows */
    }

    .webgrid-table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #8a6d3b;
        background-color: white;
    }

        .webgrid-table td, th {
            border: 1px solid #8a6d3b;
            padding: 3px 7px 2px;
        }

    .webgrid-header {
        background-color: steelblue;
        color: #FFFFFF;
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: left;
    }

        .webgrid-header a {
            color: white
        }

    .webgrid-row-style {
        padding: 3px 7px 2px;
    }

    .webgrid-alternating-row {
        background-color: #e6e0da;
        padding: 3px 7px 2px;
    }

     .webgrid-container {
        overflow-x: auto; /* Enable horizontal scrolling */
        white-space: nowrap; /* Prevent text from wrapping */
        width: 100%; /* Ensure it fills the width of its container */
    }

</style>

Views/Athena/_AthenaJob.cshtml
@model SPV_Loader.Models.AthenaViewModel

@if (ViewBag.AllItemsProcessed)
{
    <form action="@Url.Action("Download")" method="post">
        <button type="submit">Download List</button>
    </form>
}
else
{
    using (Html.BeginForm("Save", "Athena", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div>
            <input type="submit" value="Save and Next" />
        </div>
        <br />

        <div class="jumbotron">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AthenaDetails.Id)

            <div class="row">
                <div class="col-md-2">
                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.JobNumber)
                        @Html.EditorFor(model => model.AthenaDetails.JobNumber, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.JobNumber, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.DueDate)
                        @Html.EditorFor(model => model.AthenaDetails.DueDate, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.DueDate, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.PurchaseOrderNumber)
                        @Html.EditorFor(model => model.AthenaDetails.PurchaseOrderNumber, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.PurchaseOrderNumber, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.PurchaseOrderLine)
                        @Html.EditorFor(model => model.AthenaDetails.PurchaseOrderLine, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.PurchaseOrderLine, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.SalesOrderNumber)
                        @Html.EditorFor(model => model.AthenaDetails.SalesOrderNumber, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.SalesOrderNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.CustomerAccountCode)
                        @Html.EditorFor(model => model.AthenaDetails.CustomerAccountCode, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.CustomerAccountCode, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.JobQuantity)
                        @Html.EditorFor(model => model.AthenaDetails.JobQuantity, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.JobQuantity, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.AscmOrderId)
                        @Html.EditorFor(model => model.AthenaDetails.AscmOrderId, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.AscmOrderId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.EndCustomer)
                        @Html.EditorFor(model => model.AthenaDetails.EndCustomer, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.EndCustomer, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.ActivationSystem)
                        @Html.EditorFor(model => model.AthenaDetails.ActivationSystem, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.ActivationSystem, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.ProductType)
                        @Html.EditorFor(model => model.AthenaDetails.ProductType, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.ProductType, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.ErpMaterialCode)
                        @Html.EditorFor(model => model.AthenaDetails.ErpMaterialCode, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.ErpMaterialCode, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.IntegratorPartID)
                        @Html.EditorFor(model => model.AthenaDetails.IntegratorPartID, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.IntegratorPartID, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.IntegratorID)
                        @Html.EditorFor(model => model.AthenaDetails.IntegratorID, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.IntegratorID, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.ActivationType)
                        @Html.EditorFor(model => model.AthenaDetails.ActivationType, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.ActivationType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.PartNumberSku)
                        @Html.EditorFor(model => model.AthenaDetails.PartNumberSku, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.PartNumberSku, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.RetailBarcode)
                        @Html.EditorFor(model => model.AthenaDetails.RetailBarcode, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.RetailBarcode, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.RetailBarcodeType)
                        @Html.EditorFor(model => model.AthenaDetails.RetailBarcodeType, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.RetailBarcodeType, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.LabelFor(model => model.AthenaDetails.Channel)
                        @Html.EditorFor(model => model.AthenaDetails.Channel, new { htmlAttributes = new { @class = "form-control custom-form-control" } })
                        @Html.ValidationMessageFor(model => model.AthenaDetails.Channel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <!-- Additional textboxes for the extra column can be added here -->
                    <div class="form-group custom-form-group">
                        @Html.Label("Additional Field 1")
                        @Html.TextBox("AdditionalField1", null, new { @class = "form-control custom-form-control" })
                    </div>

                    <div class="form-group custom-form-group">
                        @Html.Label("Additional Field 2")
                        @Html.TextBox("AdditionalField2", null, new { @class = "form-control custom-form-control" })
                    </div>

                    <!-- Add more fields as necessary -->
                </div>
            </div>
        </div>
    }
}


<style>
    .custom-form-group {
        margin-bottom: 15px;
    }

    .custom-form-control {
        width: 90%; /* Adjust the width to make the inputs narrower */
        margin-right: 10px; /* Add space between adjacent text boxes */
    }

    .form-horizontal .col-md-2 {
        padding-right: 10px; /* Add space between columns */
    }
</style>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}